[package]
name = "glpi-vsphere"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
glpi-core = { path = "../glpi-core" }
glpi-inventory-local = { path = "../glpi-inventory-local" }

async-trait = { workspace = true }
quick-xml = { workspace = true }
reqwest = { workspace = true, features = ["cookies"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
