[package]
name = "glpi-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "glpi-agent"
path = "src/main.rs"

[dependencies]
glpi-core = { path = "../glpi-core" }
glpi-discovery = { path = "../glpi-discovery" }
glpi-inventory-local = { path = "../glpi-inventory-local" }
glpi-transport = { path = "../glpi-transport" }
glpi-scheduler = { path = "../glpi-scheduler" }
glpi-http = { path = "../glpi-http" }
chrono.workspace = true
clap.workspace = true
tokio.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
