[package]
name = "glpi-agent-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
serde_json = { workspace = true }

[dev-dependencies]
glpi-core = { path = "../glpi-core" }
glpi-transport = { path = "../glpi-transport" }
glpi-inventory-local = { path = "../glpi-inventory-local" }
glpi-discovery = { path = "../glpi-discovery" }
glpi-vsphere = { path = "../glpi-vsphere" }
tokio = { workspace = true }
wiremock = "0.6"
