[package]
name = "glpi-inventory-remote"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
glpi-core = { path = "../glpi-core" }
glpi-inventory-local = { path = "../glpi-inventory-local" }
async-trait.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true
